#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tex2quiz"
name = "Tex2quiz"
description.en = "Automatically create a quiz from a simple text file"
description.fr = "Créer automatiquement un quiz à partir d'un simple fichier texte"

version = "0.0.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://text2quiz.vercel.app/"
demo = "https://text2quiz.vercel.app/"
code = "https://github.com/eyssette/text2quiz"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/eyssette/text2quiz/archive/db0f50c1b9879a377f1fd38bcb2049f632b6a688.tar.gz"
        sha256 = "eeef9e0b61a47567d172cb332ace32d8b10b89bb1da3507675e324a95b5306b9"
    
    [resources.ports]
    main.default = 3000

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
